### ISSUE TITLE
Request for nano support

### ISSUE THREAD

**Issue by jrjhealey** [bioSyntax/bioSyntax#10]
Hi all,

This looks like a really cool tool. I'm sure you have a long list of tools you'll add support to, but I'd like to particularly request `nano`/`pico`. As a POSIX standard tool, it's my personal favourite editor for quick and dirty work (and I've never taken the plunge to learn `vi/`vim`!)

Thanks

**Comment by ababaian** [comment]
Hey @jrjhealey; I think `nano` would be a perfect port. The colour options are a little bit limited but as shown with `less`, as little as 16 colors can go a very long way in improving readability.

We'll leave this as an open issue and let anyone interested take it up. I'd recommend starting to do the research and outlining how to write syntax files (i.e. like our dev page) to help get people on board.

**Comment by ababaian** [comment]
Looks like someone is taking up the cause @jrjhealey. If you have some free time consider pitching in ;)

https://github.com/bioSyntax/bioSyntax/issues/13
