### ISSUE TITLE
gedit-gtf: Use Robust Column Selection

### ISSUE THREAD

**Issue by ababaian** [bioSyntax/bioSyntax#15]
Hey @lazypanda10117 

When you get a chance; the **gedit-GTF** syntax file doesn't use complete/correct column selection. See below, the strand column's TAB is incorrectly selected. Can you take a look when you get a chance please?

![gedit-gtf_180108](https://user-images.githubusercontent.com/9220907/34709658-edcbe6dc-f4cc-11e7-8ef2-64f9232d399d.png)

**Comment by lazypanda10117** [comment]
Sure, I will try to fix them by next week:D

**Comment by ababaian** [comment]
Hey Jeff;

Hows it coming along?

A

**Comment by lazypanda10117** [comment]
Hi Artem, 
Sorry, I forgot about it after midterms :(. Currently quite busy these few days, so I  will most likely finish it by the end of week!

**Comment by ababaian** [comment]
:+1:

**Comment by lazypanda10117** [comment]
Fixed now :D
