### ISSUE TITLE
Manuscript Revisions -- Research and Notes

### ISSUE THREAD

**Issue by lazypanda10117** [bioSyntax/bioSyntax#23]
Some questions and topics to delve in:
1)How does syntax highlighting improve comprehension, readability, and performance on data related tasks?
2)Research on how people with Synesthesia perform on data comprehension tasks and compare the results to that of normal people.
3)Biological perspective: How does our color perception come into being? Is color perception (in particular, quick recognition of contrasting colors) essential for humans, providing us a higher chance of survival?

**Comment by ababaian** [comment]
Hey @lazypanda10117 + all,

I've drafted the rebuttal letter, please review and put down your edits / comments where this can be improved. I've highlighted the sections which we'll each need to complete (relating to your task).

### [Rebuttal Letter](https://docs.google.com/document/d/1BFd27H4dsNpjfiQnJqNUEA-V6HtTtfWQlGwYBD12XKw/edit?usp=sharing)

**Comment by Dybian** [comment]
I don't know if it is useful for the rebuttal letter but now bioSyntax is referenced by the 3 biggest bioinformatic tools registries: OMICtools [1], bio.tools [2] and SciCrunch [3]. I pushed it on the last two. 

[1] https://omictools.com/biosyntax-tool
[2] https://bio.tools/bioSyntax
[3] https://identifiers.org/rrid/RRID:SCR_016207
