### ISSUE TITLE
Survey Results

### ISSUE THREAD

**Issue by Jwong684** [bioSyntax/bioSyntax#30]
Participant information:
![image](https://user-images.githubusercontent.com/22081472/39225075-35982b26-47ff-11e8-955d-fe659437b98c.png)

What biological/scientific files do you open and look at regularly (in the last 12 months)?
![numfiles](https://user-images.githubusercontent.com/22081472/39226411-2f17dbea-4807-11e8-8b39-750a6cb39ef2.png)

When you open up a biological file, which text editors do you use?
![numeditors](https://user-images.githubusercontent.com/22081472/39233006-01302fa8-4824-11e8-8738-e75066e0f936.png)

BioSyntax UX test:
Image A:
![gtf_off3](https://user-images.githubusercontent.com/22081472/39225130-797a98f6-47ff-11e8-979f-2a24a6999eaa.png)
Image B:
![gtf_on3](https://user-images.githubusercontent.com/22081472/39225173-b16ab1c4-47ff-11e8-9288-906caf4df8b1.png)
![image](https://user-images.githubusercontent.com/22081472/39225182-bd220120-47ff-11e8-8729-08bc7d94b28d.png)
![image](https://user-images.githubusercontent.com/22081472/39225191-c618b382-47ff-11e8-8b2b-6302d2af8d31.png)

Image A:
![clustal_off](https://user-images.githubusercontent.com/22081472/39225201-d436b306-47ff-11e8-9311-3b48e8679425.jpg)
Image B:
![clustal_on](https://user-images.githubusercontent.com/22081472/39225214-dcd523da-47ff-11e8-9d3d-8a6219518a1a.jpg)
![image](https://user-images.githubusercontent.com/22081472/39225221-e60d13d6-47ff-11e8-971a-44b0e70afc77.png)

N = 72 responses

Additional feedback:
What additional features would be useful for your work if bioSyntax incorporated them? What can we do to improve bioSyntax?
-Custom colour schemes (easy to implement, colour blindness mode, easy to toggle on/off)
-Package for conda
-Easy install and easy uninstall

**Comment by ababaian** [comment]
Looks great @Jwong684, can you provide a quick summary + quantification of the written comments at end as well? I think the over-all number 1 feature is looking for more color schemes so something we should focus on at MozSprint.
