### ISSUE TITLE
Support for FSA Files Syntax

### ISSUE THREAD

**Issue by jennifertran** [bioSyntax/bioSyntax#46]
I'm wondering if it's possible to implement syntax support for FSA files which are fragment analysis data file created by DNA sequencers and analyzers.

**Comment by ababaian** [comment]
Hey jennifer. If you can find a file specification sheet for FSA files for me and tell me which software you're using (sublime/vim/gedit..?). I can most likely hammer this out in an evening.

**Comment by jennifertran** [comment]
As far as I can tell FSA is pretty much the same as FASTA files but used for analyzing different sequences. File specification can be [found here](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp)

**Comment by ababaian** [comment]
If you just want  the fasta color scheme to work with *.fsa file extensions then add the line:
`au BufRead,BufNewFile *.fsa set filetype=fasta`

to the `~/bioSyntax/vim/ftdetect/fasta.vim` file which should be stored in your `~/.vim/ftdetect/fasta.vim` folder on your system.

**Comment by jennifertran** [comment]
That works for me, thank you so much!
