### ISSUE TITLE
Update the VSCode extension?

### ISSUE THREAD

**Issue by alanhoyle** [bioSyntax/bioSyntax#49]
Hey all,

When I install the bioSyntax extension into my VSCode installation, it seems to be getting a slightly older version of the underlying JSON.  E.g. the changes present here that change the language-configuration.json and syntaxes/cwl.tmLanguage.json don't seem to have propogated there.

**Comment by ababaian** [comment]
@liyao001 can you propagate the updates to the microsoft workspace please?

**Comment by liyao001** [comment]
Ok, I'll try to update it.
