### ISSUE TITLE
Overrides existing .bashrc with .bash_profile

### ISSUE THREAD

**Issue by matthewstuartedwards** [bioSyntax/bioSyntax#51]
I use .bashrc to configure my shell, but bioSyntax created a .bash_profile which seems to be loaded first.  I noticed that aliases and other configuration from .bashrc wasn't being executed after installing bioSyntax.

Looks like bioSyntax is missing something important from .bash_profile.

```
# include .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
```

This should load any existing configurations.

**Comment by ababaian** [comment]
Good call, thanks :)
