### ISSUE TITLE
Installed biosyntax-less from apt, don't have sam-less or vcf-less?

### ISSUE THREAD

**Issue by cmdcolin** [bioSyntax/bioSyntax#52]
Just curious if those would be intended to be installed? I couldn't find it installed on my system and looked at a package file list here https://packages.debian.org/sid/all/biosyntax-less/filelist

**Comment by cmdcolin** [comment]
Kudos to having an apt package though makes installing very easy :)

**Comment by ababaian** [comment]
Check your `.bash_rc` or `.bash_profile` for an `ALIAS`, it's not a stand-alone binary just a wrapper for piping the data.

**Comment by cmdcolin** [comment]
Thanks, I went ahead and added these to my zprofile and it works now. I can close for now but if there can be an install that didnt require this manual step that would be great
