### ISSUE TITLE
Biosyntax with Jupyternotebook

### ISSUE THREAD

**Issue by allamiro** [bioSyntax/bioSyntax#54]
Can we use Biosyntax with Jupyter notebook  ?  What are the suggestions if we want to include it in to Jupyter notebook to use it with Biopython code ? extension ?

**Comment by ababaian** [comment]
That would be really dope!
Are you thinking about highlighting the markdown sections with code "``` code here ```" or in the output blocks if there's biological data like `samtools view -h mybam.bam | head -n 100 `

**Comment by ababaian** [comment]
So sorry I don't have time right now to develop this. But if you're using the bash kernel in Jupyter Notebooks, the regular command line bioSyntax will in fact work. This command is usually piped to `less` by default, but with a little bit of hacking you can remove that and make a bioSyntax `cat` to print highlighted output. I'm busy at the moment to do this, but if you're up for it it's a small-ish task and is a cool feature! Share your code.

![Screenshot from 2020-05-08 08-52-45](https://user-images.githubusercontent.com/9220907/81423509-0cfe0880-9144-11ea-855f-624e6494db75.png)
