### ISSUE TITLE
src-hilite-lesspipe-bio.sh: No such file or directory

### ISSUE THREAD

**Issue by MeHelmy** [bioSyntax/bioSyntax#57]
I tried to install without sudo
as a result, less was not able to open zipped files ex: `less something.vcf.gz` that was possible before
also, I have this error now
/bin/bash: /users/mmahmoud/.local/share/source-highlight/src-hilite-lesspipe-bio.sh: No such file or directory (I removed this directory)

How I can totally delete all files produced form the bioSyntx tool?

**Comment by ababaian** [comment]
You'll want to remove the `BIOSYNTAX` region of your `.bashrc` / `.zshrc` file in your home directory `/users/manhmoud/`. Restart your computer and the command line will work as before.

Biosyntax requires `source-highlight` as a dependency, so if you've removed that then it should be OK. There is a `biosyntax_UNINSTALL.sh` script which will remove any other folders, but mainly for `less` it's all packed into the `source-highlight` directory to be organized with the addition to your `rc` files.
