### ISSUE TITLE
About Vim highlight

### ISSUE THREAD

**Issue by Shengqian95** [bioSyntax/bioSyntax#6]
I downloaded bioSyntax-0.1-beta2.zip and unzipped it. Then I run the command: `bash  bioSyntax_SETUP.sh vim`, it telled me  that "Installation successful. Restart vim and you will now have pretty  formats! Thank you for your support!"  But I excuted the command below: `vim 01_1.fq`, nothing has changed before bioSyntax-0.1-beta2 was downloaded, and I haven't figured it out. I'll appreciate it if you can tell me how to solve the problem I faced.

**Comment by ababaian** [comment]
We're still working out the installation script; try manually installing bioSyntax
http://biosyntax.org/install#vim

Please provide what operating system you have and which version of vim are you using?

**Comment by Shengqian95** [comment]
I also ran the commands in manual http://biosyntax.org/install#vim, but it doesn't work well. These are information below about my operating system and the version of vim I'm using:
Linux ubuntu 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
THANK you~

**Comment by ababaian** [comment]
Is there any highlighting at all when you open a fastq file? What if you open another type of file like .html, is there colors in vim besides black and white?

**Comment by ababaian** [comment]
Is it working with the new instructions @Shengqian95?
