### ISSUE TITLE
Publish the VSCode extension to Open VSX

### ISSUE THREAD

**Issue by MillironX** [bioSyntax/bioSyntax#61]
[Open VSX] is a third-party registry for Visual Studio Code extensions. It is used by [VSCodium] and [Gitpod], among others. It would be extremely useful to have the bioSyntax extension uploaded to the Open VSX registry so it can be used in those places.

Instructions for uploading extensions to Open VSX can be found at <https://github.com/eclipse/openvsx/wiki/Publishing-Extensions>.

Ping @liyao001, who handles most of the VSCode extension.

[open vsx]: https://open-vsx.org/
[vscodium]: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace
[gitpod]: https://www.gitpod.io/docs/ides-and-editors/vscode-extensions#installing-an-extension

**Comment by liyao001** [comment]
I think it's worth porting the plugin to Open VSX; I'll work on it later this week.

**Comment by liyao001** [comment]
bioSyntax is now on [Open VSX Registry](https://open-vsx.org/extension/reageyao/biosyntax). In the next update, I will try to add a CD workflow for publishing both VS marketplace and Open VSX extensions.
