### ISSUE TITLE
[Feature] section folding for fasta

### ISSUE THREAD

**Issue by jayagami** [bioSyntax/bioSyntax#63]
Hi, Thanks for your great work.
Currently I am using vscode plugins.
I wondering if there is possibility to add section folding for fasta fomat files.

**Comment by ababaian** [comment]
That's a really good idea; @liyao001 ould know if it's feasible

**Comment by liyao001** [comment]
It will be very useful to let VS code recognize different sequences and add fold signs to each of them in the sidebar. I'll look into this later. For now, you can manually fold sequences by the following steps:
1. selecting lines you want to fold
2. pressing <kbd>Ctrl</kbd>+<kbd>K</kbd>
3. pressing <kbd>Ctrl</kbd>+<kbd>,</kbd>

<img width="434" alt="image" src="https://user-images.githubusercontent.com/17058337/184751952-52fa81f6-4090-4c1b-845f-a471ef7db3a8.png">

**Comment by jayagami** [comment]
Thank you for your reply, using manual folding does look better, but automatic folding is more efficient when dealing with multiple sequences.
Thanks again for your work.
