### ISSUE TITLE
Submodulize bioSyntax-sublime & bioSyntax-vim

### ISSUE THREAD

**Issue by ababaian** [bioSyntax/bioSyntax#8]
I've started a branch `submodules2` where I'm working on restructuring bioSyntax a little bit. We'll retain bioSyntax as the main development repo but the `vim` and `sublime` folder are going to be changed to submodules (nested repositories).

vim/ --> bioSyntax-vim
sublime/ --> bioSyntax-sublime

This will make vim installation via pathogen and sublime package manager much easier. A submodule is essentially a nested repository.

1) If you're cloning bioSyntax use the `git clone --recursive` to download all submodules as well. Otherwise submodules don't download on default. Or use the command `git submodule update --init`

2) I haven't worked out 'hooks' yet but as it stand right now, changes to files in `vim/` or `sublime/` require two commits and two pushes. This sends the changes to each remote repo: biosyntax and biosyntax-vim.

If in doubt; simply add/commit/push from the main bioSyntax directory only, like you normally would.

```
cd $bioSyntax

# Make some change locally
date > vim/test.txt

# Add, commit and push change to https://github.com/bioSyntax/bioSyntax
git add vim/test.txt
git commit -m "Added a fake change"
git push

# Add, commit and push change to https://github.com/bioSyntax/bioSyntax-vim
cd vim/
git add test.txt
git commit -m "Added a fake change"
git push
```

Not ideal but I'll look to improve it. Worth the trade-off for portability though imho.

-----------------------------------
[Initializing a submodule](http://blog.davidecoppola.com/2015/02/how-to-create-git-submodule-from-repository-subdirectory/)
[Great tutorial on submodules](https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407)

**Comment by Ebedthan** [comment]
Ok @ababaian
